channels:  
  - defaults  

dependencies:  
  - python=3.10  
  - networkx=3.2.1  
  - numpy=1.26.3  
  - scipy=1.12.0  
  - pip:  
      - matplotlib==3.8.2  
      - pandas==2.2.0  
      - python-dotenv==1.0.0  
      - seaborn==0.13.1  
      - tqdm==4.66.1  
      - openai==1.9.0  
      - tiktoken==0.5.1  
      - torch==2.1.1  
      - transformers==4.35.2